### ISSUE TITLE
numpy.AxisError: axis -1 is out of bounds for array of dimension 0

### ISSUE THREAD

**Issue by kexul** [ZhengyiLuo/PerpetualHumanoidControl#14]
Hi, I encountered this error when using my custom animation input: 
```
Traceback (most recent call last):                                                                                                                                              | 0/1 [00:00<?, ?it/s]
  File "phc/run.py", line 297, in <module>
    main()
  File "phc/run.py", line 291, in main
    runner.run(vargs)
  File "/home/gymuser/.local/lib/python3.8/site-packages/rl_games/torch_runner.py", line 144, in run
    player.run()
  File "/data/motion_imitate/PerpetualHumanoidControl/phc/learning/im_amp_players.py", line 267, in run
    done = self._post_step(info, done.clone())
  File "/data/motion_imitate/PerpetualHumanoidControl/phc/learning/im_amp_players.py", line 147, in _post_step
    metrics = compute_metrics_lite(pred_pos_all, gt_pos_all)
  File "/data/motion_imitate/PerpetualHumanoidControl/uhc/smpllib/smpl_eval.py", line 44, in compute_metrics_lite
    pa_mpjpe = p_mpjpe(jpos_pred, jpos_gt).mean(axis = -1) * 1000
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py", line 167, in _mean
    rcount = _count_reduce_items(arr, axis, keepdims=keepdims, where=where)
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py", line 76, in _count_reduce_items
    items *= arr.shape[mu.normalize_axis_index(ax, arr.ndim)]
numpy.AxisError: axis -1 is out of bounds for array of dimension 0
```

Here is the command and input file I used: 
```
python phc/run.py \
    --motion_file nba_test.pkl \
    --task HumanoidImMCPGetup \
    --cfg_env phc/data/cfg/phc_shape_mcp_iccv.yaml \
    --cfg_train phc/data/cfg/train/rlg/im_mcp.yaml \
    --network_path output/phc_shape_mcp_iccv --test --num_envs 1 --epoch -1 --im_eval
```
[nba_test.zip](https://github.com/ZhengyiLuo/PerpetualHumanoidControl/files/13534043/nba_test.zip)

Many thanks!

**Comment by ZhengyiLuo** [comment]
Pushed a fix. Thanks!
