### ISSUE TITLE
KeyError when loading the pkl file in sample folder

### ISSUE THREAD

**Issue by kexul** [ZhengyiLuo/PerpetualHumanoidControl#3]
Many thanks for your work! I've installed the dependencies and successfully run the following scrip to make sure I'm ready to start.
```bash
python uhc/smpllib/smpl_local_robot.py
python scripts/joint_monkey_smpl.py
```

So, I downloaded the model by `bash download_data.sh` and tries to do some inference, using the provided command:
```
## Shape + rotation + keypoint model
python phc/run.py --task HumanoidImMCPGetup --cfg_env phc/data/cfg/phc_shape_mcp_iccv.yaml --cfg_train phc/data/cfg/train/rlg/im_mcp.yaml --motion_file sample_data/amass_isaac_standing_upright_slim.pkl --network_path output/phc_shape_mcp_iccv --test --num_envs 1 --epoch -1

## keypoint model
python phc/run.py --task HumanoidImMCPGetup --cfg_env phc/data/cfg/phc_kp_mcp_iccv.yaml --cfg_train phc/data/cfg/train/rlg/im_mcp.yaml --motion_file sample_data/amass_isaac_standing_upright_slim.pkl --network_path output/phc_kp_mcp_iccv --test --num_envs 1 --epoch -1
```

But the following error occured: 
```
Importing module 'gym_38' (/opt/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /opt/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.12.0a0+bd13bc6
Device count 1
/opt/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/gymuser/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
Emitting ninja build file /home/gymuser/.cache/torch_extensions/py38_cu116/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
2023-10-30 08:40:47,111 - INFO - logger - logger initialized
MOVING MOTION DATA TO GPU, USING CACHE: False
MOVING MOTION DATA TO GPU, USING CACHE: False
Importing module 'rlgpu_38' (/opt/isaacgym/python/isaacgym/_bindings/linux-x86_64/rlgpu_38.so)
torch_deterministic: False
torch_deterministic: False
torch_deterministic: False
Setting seed: 0
Found checkpoint
output/phc_shape_mcp_iccv/Humanoid.pth
Started to play
Traceback (most recent call last):
  File "phc/run.py", line 297, in <module>
    main()
  File "phc/run.py", line 291, in main
    runner.run(vargs)
  File "/home/gymuser/.local/lib/python3.8/site-packages/rl_games/torch_runner.py", line 142, in run
    player = self.create_player()
  File "/home/gymuser/.local/lib/python3.8/site-packages/rl_games/torch_runner.py", line 128, in create_player
    return self.player_factory.create(self.algo_name, config=self.config)
  File "/home/gymuser/.local/lib/python3.8/site-packages/rl_games/common/object_factory.py", line 15, in create
    return builder(**kwargs)
  File "phc/run.py", line 209, in <lambda>
    runner.player_factory.register_builder('im_amp', lambda **kwargs: im_amp_players.IMAMPPlayerContinuous(**kwargs))
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/learning/im_amp_players.py", line 28, in __init__
    super().__init__(config)
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/learning/amp_players.py", line 23, in __init__
    super().__init__(config)
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/learning/common_player.py", line 16, in __init__
    BasePlayer.__init__(self, config)
  File "/home/gymuser/.local/lib/python3.8/site-packages/rl_games/common/player.py", line 17, in __init__
    self.env = self.create_env()
  File "/home/gymuser/.local/lib/python3.8/site-packages/rl_games/common/player.py", line 136, in create_env
    return env_configurations.configurations[self.env_name]['env_creator'](**self.env_config)
  File "phc/run.py", line 193, in <lambda>
    env_configurations.register('rlgpu', {'env_creator': lambda **kwargs: create_rlgpu_env(**kwargs), 'vecenv_type': 'RLGPU'})
  File "phc/run.py", line 88, in create_rlgpu_env
    task, env = parse_task(args, cfg, cfg_train, sim_params)
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/utils/parse_task.py", line 60, in parse_task
    task = eval(args.task)(cfg=cfg, sim_params=sim_params, physics_engine=args.physics_engine, device_type=args.device, device_id=device_id, headless=args.headless)
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/env/tasks/humanoid_im_mcp_getup.py", line 29, in __init__
    super().__init__(cfg=cfg, sim_params=sim_params, physics_engine=physics_engine, device_type=device_type, device_id=device_id, headless=headless)
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/env/tasks/humanoid_im_getup.py", line 59, in __init__
    super().__init__(cfg=cfg, sim_params=sim_params, physics_engine=physics_engine, device_type=device_type, device_id=device_id, headless=headless)
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/env/tasks/humanoid_im_mcp.py", line 22, in __init__
    super().__init__(cfg=cfg, sim_params=sim_params, physics_engine=physics_engine, device_type=device_type, device_id=device_id, headless=headless)
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/env/tasks/humanoid_im.py", line 46, in __init__
    self.load_humanoid_configs(cfg)
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/env/tasks/humanoid.py", line 237, in load_humanoid_configs
    self.load_smpl_configs(cfg)
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/env/tasks/humanoid.py", line 426, in load_smpl_configs
    self._load_amass_gender_betas()
  File "/opt/isaacgym/motion_imitate/PerpetualHumanoidControl/phc/env/tasks/humanoid.py", line 715, in _load_amass_gender_betas
    gender_betas_data = joblib.load("sample_data/amass_isaac_gender_betas_unique.pkl")
  File "/opt/conda/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/opt/conda/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/opt/conda/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 242
```

Any clue what I'm missing?

**Comment by kexul** [comment]
Quite confusing now, when I load the file manually by `python -c "import joblib ;joblib.load("sample_data/amass_isaac_gender_betas.pkl")"`, it loaded correctly.

**Comment by kexul** [comment]
The `amass_isaac_gender_betas.pkl` could be loaded without error, maybe the `amass_isaac_gender_betas_unique.pkl` is broken?

**Comment by kexul** [comment]
I've tested the four pkl file in sample folder, the `amass_copycat_occlusion_v3.pkl` and `amass_isaac_gender_betas_unique.pkl` could **not** be loaded, the `amass_isaac_gender_betas.pkl` and `amass_isaac_standing_upright_slim.pkl` could be loaded.

**Comment by kexul** [comment]
For your information, I'm using python3.8 with joblib 1.1.0.

**Comment by kexul** [comment]
Ok, the error disappeared after upgrading joblib to 1.3.2.
