### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by Anonnyyy** [ZhengyiLuo/PerpetualHumanoidControl#73]
Thank you  very much! : )
I met some problems when running:
`python scripts/vis/vis_motion_mj.py`
it shows:

>****************************** Current motion keys ******************************
Sampling motion: tensor([0])
standing
>*********************************************************************************
>0it [00:00, ?it/s]pbar 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "scripts/vis/vis_motion_mj.py", line 105, in <module>
    motion_lib.load_motions(skeleton_trees=[sk_tree] * num_motions, gender_betas=[torch.zeros(17)] * num_motions, limb_weights=[np.zeros(10)] * num_motions, random_sample=False, start_idx=curr_start)
  File "/home/anony/omnigrasep/PHC/phc/utils/motion_lib_base.py", line 249, in load_motions
    res_acc.update(self.load_motion_with_skeleton(*jobs[0], None, 0))
  File "/home/anony/omnigrasep/PHC/phc/utils/motion_lib_smpl.py", line 116, in load_motion_with_skeleton
    for f in pbar:
  File "/home/anony/anaconda3/envs/rlgpu/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
TypeError: 'int' object is not iterable

看起来像是motion import失败了， `motion_file = "sample_data/amass_isaac_standing_upright_slim.pkl"` 导入的motion list是空的。请问您有遇到这样的问题吗？

**Comment by ZhengyiLuo** [comment]
Hi! 

请pull最新的代码；应该是我在改multiprocessing 的时候出了点问题，现在应该可以了。
